// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://coiazfubrveyigtqmzfz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNvaWF6ZnVicnZleWlndHFtemZ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0MDc0NjIsImV4cCI6MjA2NTk4MzQ2Mn0.PXJ25cK9xnEYzrm1gVjtFhzuny5trnJ7k_CSBbZL9YQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);